### ISSUE TITLE
Ctrl+C does nothing?

### ISSUE THREAD

**Issue by matkuki** [ephja/nim-glfw#11]
Line 83 in file https://github.com/ephja/nim-glfw/blob/master/examples/events.nim#L83 :
```nim
setControlCHook(proc() {.noconv.} = done = true)
```
does nothing. I also tried using a proc with an echo in the setControlCHook hook and nothing was echoed.
I'm guessing because glfw overrides the keyboard hook?
This is on windows 64-bit using Nim 0.12.0. 
Can you check?

**Comment by ephja** [comment]
This hook is for when Ctrl-C is pressed in the terminal or when SIGINT is sent to the process in some other way

**Comment by matkuki** [comment]
Right, you have to focus the terminal window, then it works.
Sorry, my bad.
