### ISSUE TITLE
included glfw source does not build with MSVC

### ISSUE THREAD

**Issue by barcharcraz** [ephja/nim-glfw#12]
I'm using MSVC version 19.00.2306 for x64 (the version included with visual studio 2015) on windows and compiling a project using nim-glfw without -d:glfwDynlib results in linker errors for pretty much every GLFW function.

Perhaps glfwDynlib should be the default for some configurations

**Comment by ephja** [comment]
I do agree that dynamic linking by default is better

**Comment by ephja** [comment]
It is the default now
