### ISSUE TITLE
Consider using cross-platform defaults

### ISSUE THREAD

**Issue by flyx** [ephja/nim-glfw#15]
Currently, the defaults of `newGlWin` lead to errors on OSX. You have to at least supply these parameters to make it work:

``` nim
var win = newGlWin(version=glv32, forwardCompat=true, profile=glpCore)
```

(Or a legacy OpenGL 2 version)

I think it would be less frustrating to newcomers to have defaults that work out of the box on all sufficiently recent major platforms.

**Comment by ephja** [comment]
I do agree that it needs to be changed, but is forward compatibility actually required? It seems like a good default though, and I think the default version should be 2.0.

**Comment by flyx** [comment]
Forward compatibility and core profile are required for 3.x on OSX. I also think that the default version should be 2.0, because having 3.2 with core profile strips away some of the entry-level OpenGL features.

**Comment by ephja** [comment]
@flyx Actually, I think the defaults should be the same as those for GLFW
