### ISSUE TITLE
Nimble reinstalls the package on every build

### ISSUE THREAD

**Issue by RSDuck** [ephja/nim-glfw#18]
I think it's related to the version tag 0.21 which doesn't match with the version inside the nimble file 0.2.1.

It is very annoying because it results in much higher build times.

**Comment by dom96** [comment]
Yeah, this sounds likely. Probably an issue that Nimble will have to tackle eventually too, but I wonder whether it should simply reject installation if the version tag doesn't match.

**Comment by RSDuck** [comment]
I played a bit around and my assumptions weren't right. The reason why Nimble redownloads the package on every build is another. 
The true reason is that inside of Nimbles index, this package is registered as nim-glfw. But inside of the nimble file it's registered as glfw. 
This means that Nimble finds this package only under the name nim-glfw, but after downloading it, it gets saved as simply glfw. So the next time, the package will be redownloaded, because the package nim-glfw isn't installed.

If you add nim-glfw as a dependency and let Nimble download it once or use nimble install manually on this package and then change the dependency to just glfw everything works(except updates for the package).

BTW the other glfw wrapper for Nim suffers from the same problem(https://github.com/rafaelvasco/nimrod-glfw).

The easiest solution would be to simply change the name inside of the .nimble files to the repository names

**Comment by RSDuck** [comment]
the new package file has fixed this issue
