### ISSUE TITLE
Missing nimble file

### ISSUE THREAD

**Issue by stisa** [ephja/nim-glfw#23]
Looks like the nimble file was deleted in https://github.com/ephja/nim-glfw/commit/7ad43b053b2d36e60b93787a74602c21da0d2066

Was it intentional?

The package is still listed in https://github.com/nim-lang/packages/ and the last version tagged ( 0.2.1 ) is still installable.

**Comment by ephja** [comment]
It was not intentional. I've re-added it. Thanks.
