### ISSUE TITLE
Won't compile with '--threads:on' for nim 0.17.0-Stable

### ISSUE THREAD

**Issue by cheetelwin** [ephja/nim-glfw#27]
I've been building something on top of your glfw wrapper and I ran into an issue. Any reason compiling with '--threads:on' would cause a compiler crash?

```
Hint: used config file '/home/jackson/Tools/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: rim_viewer [Processing]
Hint: glfw [Processing]
Hint: wrapper [Processing]
Hint: tables [Processing]
Hint: hashes [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Error: internal error: getTypeDescAux(tyGenericParam)
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

I've narrowed it down to somewhere in here https://github.com/ephja/nim-glfw/blob/master/src/glfw/wrapper.nim. 
Here's the output from koch temp c https://hastebin.com/inimeyatuc.lua

**Comment by ephja** [comment]
I have no idea. Try compiling with the latest revision of Nim and nim-glfw (I made a lot of changes recently). Provide a test case if that doesn't resolve the problem.

**Comment by cheetelwin** [comment]
Well it still won't compile on 0.17.0-Stable. However the good news is it's now not breaking the compilation. 

```
glfw_git/src/glfw.nim(677, 11) template/generic instantiation from here
glfw_git/src/glfw.nim(671, 28) Error: type mismatch: got (Table[glfw.WindowHandle, glfw.Window], proc (t: Thread[handle.TArg]): SysThread{.inline.})
but expected one of: 
proc getOrDefault[A, B](t: OrderedTableRef[A, B]; key: A): B
proc getOrDefault[A, B](t: OrderedTable[A, B]; key: A): B
proc getOrDefault[A, B](t: Table[A, B]; key: A): B
proc getOrDefault[A](t: CountTable[A]; key: A): int
proc getOrDefault[A, B](t: TableRef[A, B]; key: A): B
proc getOrDefault[A](t: CountTableRef[A]; key: A): int
```

 It looks like some weird template pragma bug, but I'll see if I can't get it tracked down and get threading support in a PR.

if you want to reproduce a minimal example is just

example.nim
```nim
import glfw
```

```bash
$ nim c --threads:on example.nim
```

**Comment by ephja** [comment]
There's a type in the `threads` module named `handle`, but I made the template `dirty` and that seems to have fixed it.
