### ISSUE TITLE
Test the library on Linux and macOS with static and dynamic linking

### ISSUE THREAD

**Issue by ephja** [ephja/nim-glfw#34]
I have only tested the latest version on Windows so far and I don't access to a Mac computer.

**Comment by ephja** [comment]
I have tested it on Linux with X11 and Wayland and it seems to work.

**Comment by johnnovak** [comment]
I can take care of the Mac stuff. In fact, I have tested static linking on OS X today and the compilation fails straight away, some changes were needed... I'll create a PR soon, probably tomorrow.

I have just tried static linking on Windows using the official 64-bit Nim 0.17.0 distribution (gcc (x86_64-win32-seh-rev1, Built by MinGW-W64 project) 6.3.0) and it fails. I just tried to compile the minimal example:

```
nim c -r -d:glfwStaticLib minimal.nim
```

Does this work on your machine?

**Comment by ephja** [comment]
I think I just need to change one line in a macro for it to work on the last release.
