### ISSUE TITLE
Compile time assertion fails

### ISSUE THREAD

**Issue by RSDuck** [ephja/nim-glfw#37]
Atleast for me on devel, [this](https://github.com/ephja/nim-glfw/blob/master/src/glfw/wrapper.nim#L351) results in a compile time error, due to this [assertion](https://github.com/nim-lang/Nim/blob/devel/lib/core/macros.nim#L983). By removing the `[0]` everything works perfectly as it should. 

I don't know if it worked previously, but I can't imagine that they changed the AST format of pragmas.

**Comment by ephja** [comment]
@RSDuck something was changed. not that it really matters anymore since a new version of Nim was released after the fact.
