### ISSUE TITLE
Compilation fails: "Error: ordinal type expected"

### ISSUE THREAD

**Issue by RSDuck** [ephja/nim-glfw#41]
I'm using Nim from today's [devel](https://github.com/nim-lang/Nim/commit/8b638ae59991009d6b0b08af2bcf48c11a04eaa2) and I get the following error when compiling any code which utilises glfw:
```
Hint: used config file 'C:\Nim\config\nim.cfg' [Conf]
Hint: used config file 'c:\Users\Kemal\Desktop\nim-glfw\examples\nim.cfg' [Conf]
Hint: system [Processing]
Hint: events [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: glfw [Processing]
Hint: wrapper [Processing]
Hint: macros [Processing]
Hint: tables [Processing]
Hint: hashes [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
c:\Users\Kemal\Desktop\nim-glfw\glfw.nim(81, 17) Error: ordinal type expected
```

It seems to be related to the `ModifierKey` enum which supposedly can't be used in a set(anymore?).

**Comment by RSDuck** [comment]
this seems to be related: https://github.com/nim-lang/sdl2/commit/e6eba4aa213df997f35bd6a3fb3f1a8144e576db

**Comment by johnnovak** [comment]
I have no plans to fix this for the devel branch in the foreseeable future, so you can either put together a fix PR or wait :+1:
