### ISSUE TITLE
Opengl does not seems to be working.

### ISSUE THREAD

**Issue by stavenko** [ephja/nim-glfw#8]
Hello. I've just tried nim-glfw and found out, that in certain circumstances this thing is working. events.nim really opens a window and produces output (keys and mouse events).

But then I'm trying to draw something on the window. But, any call to **gl**BlaBlaBla() creates SEGFAULT, just like no one ever initialized OpenGL context.  

I tried to find out how to initialize context, but it seems not very clear to me. So, any thoughts, where could I check something, and then make it working?

My system is Mac Os X 10.10.1, nim 0.11, opengl -> https://github.com/nim-lang/opengl
And,  they're demos are working (in Opengl 2.1 only) fine on my PC.

**Comment by exetoc** [comment]
did you forget to call loadExtensions? https://libraries.io/github/nim-lang/opengl

**Comment by stavenko** [comment]
Well, I supposed to loadExtensions in my first-ever program in nim with OpenGL. But it looks like I have missed something else, because I just _carefully_ recreated project and got good result: finally drawed red triangle with array buffers and shaders on my Mac OS X pc. 

Thank you for your response, it showed me, that I'm doing something wrong, and at this point I cannot even tell what exactly was wrong. 

Thank you for you job. I could even send you my example of red triangle, which uses glfw3 and opengl  (after I clean it a little and build both on mac os and linux without commenting-uncommenting anything). It might be useful for new comers.

**Comment by ephja** [comment]
Sorry, I forgot about this. There are a few examples by now, but create a PR if you would like to add something else to the list.
