### ISSUE TITLE
Example `events.nim` doesn't run

### ISSUE THREAD

**Issue by dgellow** [ephja/nim-glfw#9]
I have an error when I run `nim c -r events.nim` from within the examples directory.

```
/home/sam/Development/Nim/game_engine/nim-glfw/examples/events 
Traceback (most recent call last)
events.nim(102)          events
glfw.nim(825)            update
glfw.nim(814)            swapBufs
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed
```

As the stacktrace says the error occurred in `glfw.swapBuffs`:

``` nim
proc swapBufs*(o: Win) =
  wrapper.swapBuffers(o.handle) # <— o.handle shouldn't be nil

# [...]

proc update*(o: Win) =
  o.swapBufs()
  pollEvents()
```

**Comment by exetoc** [comment]
I would assume that it's because "failIf" works differently now.
What happens if you add "assert result.handle != nil" below this line https://github.com/exetoc/nim-glfw/blob/master/lib/glfw.nim#L669 ?

**Comment by exetoc** [comment]
failIf appears to be working correctly for me, so I dunno what's wrong

**Comment by dgellow** [comment]
I'm trying to investigate with gdb but I have little experience with it so I am not really sure if I'm not doing something wrong.

By the way I was wrong about the value of `o.handle`, it doesn't seem to be nil:
```
(gdb) print o.handle
$4 = (void *) 0xf39520
```

I have isolated the error to `_glfwPlatformSwapBuffers` in the file `glx_context.c`:
```c
void _glfwPlatformSwapBuffers(_GLFWwindow* window)
{
    glXSwapBuffers(_glfw.x11.display, window->x11.handle); // <— 
}
```

If I step into `glXSwapBuffers` I get a segfault:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2a4194a in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
```

So the problem seems to be with the driver of my graphic card ?
I will do some research about it then close this issue as it seems to be not related to your library.

**Comment by exetoc** [comment]
That might be it. Other people seem to have problems with that driver. It could have something to do with GLFW itself, but that seems less likely. You could try setting "version" to something lower than glv30. It usually gives you the highest working version, if any, below the specified version if it fails, unless all versions fail, but it might be that a faulty driver could cause that to fail too.

Do any other OpenGL applications work for you?

**Comment by dgellow** [comment]
Yes, other OpenGL applications work fine. I just tested to compile and run the helloworld from [this quick introduction to glfw v3.0](http://www.glfw.org/docs/3.0/quick.html) and it also works without problem.

**Comment by dgellow** [comment]
I tried to change the used version value from `glv30` to `glv10`, I got the segfault everytime.

**Comment by dgellow** [comment]
I have found a solution! 
If I call `win.makeContextCurrent()` before `while not done and not win.shouldClose:`, it works.

**Comment by exetoc** [comment]
I'll look into adding checks for that in debug mode

**Comment by ephja** [comment]
and/or make the context associated with the window the active one, before giving the user a window, by default.

**Comment by ephja** [comment]
@dgellow I went with the second approach.
